import os
import threading
from tkinter import *
from tkinter import ttk
from tkinter import messagebox
from tkinter import filedialog
from image_rounder import round_image

file_separate_sign = "|"
max_progress = 100
icon_data = "R0lGODlheAB4APcAAAAAAAAAAAEBAQAMGAAQHQATIgAWJwAZLAAcMQAgNQAjOgEmPwIpRAMsSQMvTQQEBAcHBwYyUAg0UgsLCwo2VAw4Vg4ODg46WBAARBERERE9WxIAABMBSBM/XRQUFBVBXxcESxcXFxdDYRlFYxoAABoHTRsbGx0JURxIZh4eHh5KaCEAACEMVCBMaiMPVyIiIiJObCUAACUlJSRQbicRWyZScCkAACkpKShUcisUXipWdCwAAC0WYSwsLCxYdi5aeDAAADAYZTAwMDBcejMzMzJefDQAADQaZzRgfjYAADccazY2NjZigDgebThkgjoAADsgcDo6OjpmhD0AAD09PTxohj8icz5qiEEAAEFBQUBsikJujEQmeURERERwjkVxj0YAAEcofUkAAEhISEh0kksqgUtLS0t3lU0AAE4thU5OTk56mFEAAFAviFF9m1QAAFQxi1VVVVSAnlczj1eDoVkAAFsAAFs2klqGpF03lVxcXF2Jp14AAGACAmCMqmIDA2MFBWI7mmNjY2OPrWUHB2U+nWcICGaSsGgKCmlDoWmVs2oLC2pqamwNDW0PD21GpWyYtm8QEG+buXESEnEUFHBKqXFxcXKevHQVFXUXF3RNrHSgvnYYGHdRr3h4eHikwnobG3pUsn0eHnyoxn8gIH5Xtn9/f4FbuYCsyoIjI4QlJYVevISwzocoKIaGhokqKohiv4i00otlw4wtLY2NjYy41o8wMI9pxpEyMpC82pJsyZOTk5Q1NZVvzJTA3pY3N5k6OpjE4ps8PJp00JqampzI5p4/P55506BBQaGhoaDM6qJ+1qVGRqTQ7qaD2alKSqioqKjU8qqI3a1OTqzY9q6M4K+vr7FTU7OR47VXV7eW5ra2trlbW7ub6r1gYL29vb+g7cFkZMOl8MTExMZoaMep88ptbcvLy85xcdJ1ddLS0tZ6etjY2Np+ft6CguKGhuaNjeqUlO6bm/KiovapqfmvrwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAUKAAAALAAAAAB4AHgAAAj/AAEIHEiwoMGDCBMqXMiwocOHECNKnEixYkQTPZZY3Mix48YQrs698EiypMmDUaBpPMmy5UYherYJcUlT4hIhJkwKcTVuZs2fC4WccxXCpAw9tL5R6SGRCBGmQC0ugRaFpYkulrapi9IjRUMZMs4luxG1opBtenyeDCFDkKlk49T16CFECJElN2/cCBHihStr7M55LStRyDhXK1mCAPHihV0qyax9O6eu8rZkrjxRSSEo6S4PNS3coFJ4yTdaeqC2BEEjTJ48bYTMnU2b0RiMaiypdfki2TkhMhqmsKtuG60uoGvSSFMJ1i1dunrpkrWqUyG/PaKkyGDiRo+cNFOc/2NnjRbfEHqF4K0ru4e6ccloMZJR9KeLMJqGaesGTpw4cNXo8ggRu7wggwkp6LHLNqq15MEupwmSAhFmeOJKMt9Uds431iRDBRGyybAYUCccMUcougyzDDbddCMNLEJ8Y4oaw8kQBzS//SSEJWp8NwYjtAUpRBuvhUEDCGWxYAWRhVRyyjHOCLgEMTSGEIUMY1hDWk0mvHCDCRmkwJUrLxTSySqyRAfdLbBUkgYNhJWQgxJhEBlKL7c8IgQxjNxQRghjyEDFN4m51MM2u0hoggwv7HLDI7pU099/3WgzjCZhuEAYACwEwUUemshyiya99VlJIi8IIkMU1gRnERA2BP91DjRxyHBDCmr8JQQs0rSIzTLD6BLKHEecsCkLSsxRySqnkGqNKzeUcksnPTCSQg+fVfQEGHywkURQ1gQaRQi4JrMEpM4cc0olhcBmBQubAuDCp4+soskN3+wSwirH9NKJELS8kIIn4zT4EBiTpCJKJn9MoRC+VMiQRQhl3OAKMUI8cksvocAWhhI5lIBQXTIEcNK8bdSbAmYy3FKNNHkukYwQSsigkkRokCIMM8b8koohDiNkwjZX6vFCIpXcwEgyL2hyiyya5MFFEPAOlMAAAIRgGDGWZGDSCTks+cgNid6wiqTanJICIy/AkUcKrmzjqkNYcPJMOOaQk40wqfT/YQRCFuzSlScvdHJLKRZb0/Qpq1QyhxJVA5CACAkIUdmzBncE9pI3eKLHDXdWI442pbxAuJOJ9GBN5gk9wYkw4azjjjvmXMNLJFgc9MI4plyLcSe9HLNKCBDeoMkqj0itqeRO1JBAcbTEsZtHJ4B9wxKWdNGDJqfAMgw42ITSqAynOHOLDKaMM/dCWLzCTTruwPNOOt4II8of3xbUAzQvKNHDN1nQmDSqcb4LpQB5beCCphKAAjc4IQGmsM36qHeCRXmuBzKAQyEe0RxtYEMTquuBLsCxjNQJriFPeAXs1rEOdGSjZ7ZIRSOCNpAUWMMTKcgDHEJgiRScQhsAWoXS/xz1iDZYIQcJKIIPzuAHHSQgUCcxUA8wAxwWhK0MRDoFNqSRgjikoBLOKEf40OfFCRoEDb/wRjvW4Y1fcIISjsAEJzCBP4LIgBg9SMS6XmCKF5RCG+KoBseUZoobGDEBqBhEEa7gBh1IIAE6uQExXCGIF5igBJg8gQuCYAU4lKIay5DBfDqBjXJoAxaFwFIPJJSQHZDiGuhAxzRm0YcpyACDhphEI3InkBRAwxMtc8YpZFCgUGADHMOARbOEoAZPJKABmxiEHJjwAyfMYAQNYMmBkkOQEmwyDZ0AVg9M0YM/irFNKViCGk6IkCcIwxvm8MYrCPGCHnTBDFS4gR0aYf+IvwGAmHlcBjh0sb/tYeOUlXhEIeAggwaw4hJyOIMTijCEIdSgBSNYQJzmlQhYhEJmuwLiMULRiU7IwAxwMSMAYmA3b9huET2gQhyIoQ5XBKoOQANACkxRK2OWwxmVSFAKpIGNU8CmDM9kBSToIIUh6IAMeMDDGa7wgxFAsiwlmkMihFoI/UhjXU+CxSqhoQ4zAiEVzGBGK9gwGg/0wBLJMIMAIIAFQwDiCa7QgwwKAQttiNGklpDBMqpRCjg8UxmxkMQatOCDH7hBEp9AxSgO4QUcZJMwOeBCG9oiA2NiI0+BuIWLQlGtZMiNIFOIhC2EwYk/WEAIIRCAAG4goQD/CGAHfWgEGBixhC/CopSk64EreqCiZzYjsX4gQxFUcAY5XIIVwWhGM1jhhy1oQAGEKREUxtkDWFRjGJWAwxxk0Q1s6EITbaFFMjAIgBXYARSzAAUfsBCCLjBiArMFpgAekAE+YIINtQpDJUJxDHCccopCMEACapGLSxxiDUVogQqu4FxU+EIZ1IiGLz5xBhEw4FgsWMIulnCLYXRiDlywwicFCQuT5oYWxAgBEAhBilT8AQskMEEWXKEGgBnnBmPwABsyYYgnmCAPjzCcNCxViAUsQLGj2MQerlCDCNTgC3KQxChiceFoRKMYrKCDChZwAMJwYJU9mMMpThEILtCA/wuJSFGKhlEKMeVmCVMghCj6NgUSyMADboGLGojJCAu8gROpwMKS8qDHY2ADGwu4Qi3WgAM3aEEFF2iACqSwBjxc4hOsyEUtikHqWuBBBw24alQwsKMewIFdZeABC2gAhUCUQhbL0MYxgrqELBgBDI2wBTAwgYYVANkEcfDELiSTDD0IoA6pGDYbntCGOTyiFMOwgAVQ4AcnXKAGIlhAAygggkVi+RCfPgSDfVGLQeAgAg0o86qFQE4uwCEMPCBIE+AQimFgwxmlaEMKbpAENryOGaKogw0goAbuZCHZguBxAOwgjL1log5TmAIXAmEBU1ggAleYQaoTkABxd6AFOP9gghS+4IY9SEERm0DFJdwwg0xjd9606IESjgCnghwhEKeYziPCAAQjYMEOnPgFM2wBiCkEIAR6yIAgTKCHFGTBAwEAxDTCMY1WLELbIbCAJfSwhAwomOQCIbm4KdABFNRgCEgYwRfosIc1+GAEI+jAh8sypR64IHIFCcIdCnEHICRhW2KwQyReYQxgTKIOJGC4BWybAgFYIAMQmAQyrvGKLtHWFB4YwxJMIAATRMEEUChIycctgbZfYAROaF7eL3qBmwOFCMkQUUJYwAOj/8ERoHiFKBzBB1EY4xmzMASOH/AAQViACK99gA1aYQxkQMAStBgHFaa+BAjAgQsy6IL/DI5gkAQcgAEt8MEVvOCDTI+gCmuYagv2DhSApQBJ7cTCIlKBi2dwIxzZgAy/YAvGkA3MAAp18AQxYHmCEAdRkAEZAAbA8AsQAAGOgTFm8AK3ZQRKcANx0AP4p3oX4ANO4AaK4AV65wN0MAqs4HISUBYy4AncZBBTMAm2gAvCsH/CgA7xNA3McA3e4A3DBjQkEABGqG0rkAkUmAK70BOMEFsBEANYgAZG8FaFQhDPdAEzsAV+8AUtgAJOcAixEAyXsAYfYHs18QJVgRBYkArPkA7mwA2v8Azt8A5rFA7M8E7k4A3PwAuLgHFGYHRsgAi4kAIpYAYpYAkQ0BefswNg/zBtMuAKRJAQzyQBm4YDKNACX6AIuaAMubAHNYCG4TE9AzEFtsAN7RBP1/AM12AO65A33sALhjANv3ANegMMnEAIbCAGhAAKrQA3npAFFhAHGfACekAMN/BrgMAGRuAJpGg1DTBuH+AAFNACXiCGzaAMn1AEl/UTM0gQrsMM4YAO3OCDyIAM08ANQHgNuAiE5uAObISLiAAIi3AtiYKIHqBtSzAGnlCBYrAId1UrCkFyDeAAC0ABKMAEcvAJXPYJV0ABUfGNA4EFtnANeEOLpBB8vNCHzyAMrKhC6CAP72AOz8AJk2CPpmAGXZEJKzAFFgABKfACVAABbLAImIAFvf81kAkgAdj0AR/QAlXgB3IQC5dQBRAJFBZwEFjQCMZgi+HADR2JBn0QCbOwCMzwCsDADJkwDfAgD+3QRpMgFFyDiLbAC68QA2CwARAQBaYAAUZgBwnTB08wGAhBciMwBCWnAA2whUPwCYcgBS8YLxNpC88wDd4wDaJACG/ABlhQV2iAC32gQosgDPB4Db9wLeeQkl3BCQTICzuABhUoA0IQA0kACJmgCjfmT5Q4AlugABUwAxLgAEOAAoOAB0wQmIJpBKTwDMiACwZoDK9ACpPwBmCQBAhjcK+QCcJgO9fyDZTUFalgC6LwCtJZcBDwdJ4QA0+ACKLAC4QgBk+wEAn/8AFMQAE1IAUdYJ4X4AVnUJ6CKRBTMAvlOA3XAIQA2Juq4Ag2UAdYUAecgAiZkAk2hBqbwQubx3mNwAuI8AR9sAFPNwYrAAaO8ArMMAmGAAbi+QE4MAJuQAcf0AEOUAE6UASO9J4AgAbTkA7ZwIfAyQlgMAVGYANowIw7gAW/NnDE4AkqmQK24A3psA7kgAyvkA2v8ASOEANGuARSSAm/gJiUAAYxMJA/OQKQsAlk0AKZVgEj8AHduClTkApqFA7PAAytYAhscJ+2YAM2ACtG0BeuYAlxsBmcwAuoCA/wEE8BKApTAAo7YIQhsANioJzcwAypIAZAMJARsJ6XgApu/4AEFLAAKACiqrYpWIALPhqLjmAIhzkLjsCftuAIaGCEURAHatBbFsB4v0AO7wAP7rCi3pANvPClfRoAELADBmcM5oAMoGAHvFSXIVoEe3AIWjAEDYACUvADGqBR8fIEaJWq3OANAGgLCIgFavoAExACgkAMpicEFlAHfcAJr8AL6OAO7wCP4cALoqCnqfAERhgAQHBozBCkyOAIbBClCLEAsVkBTHAFKpCCdOAGOEB/hAEGv5ANqYCH10CofYAFQLACzEcFcIU9fQEBf9AHmaAwxtAO8BAP8xAP5sAwogAGpAAG7WoEb6CcLnUNpLAIqmkQC9ABjyRuC6AAB6AFkP8wCD4gsFEBBKRgDOEwC+QADM/QCoSwA0bAmAIAgc33AmpQgY2ACIvAC2KKDu/AsfQwD+ugMMzQB2KQCitghAWHsjuTCY0QngehAC0AA+FWARpwARJwAXQQC4dQAYL5BK3wDN5gDOjwC8CACDbABjYYANu3CyZgBhYQAhAQCYvAmYa5h+kQD/RQD++ADjuTDYgABnwKtv75DORgkbMQCWJAAgcRaUigAg2ABGSgBSOgAoOQC3TQpTuLCMCQDeQQDuRgC5xgBGLQTylweS8QByYQAhlgBomLCJNwsbzADL/QDvNQD/Swqq9oDpQwBbkbACuABd96DemQir9ACm8QKwb/0QByoAUt0ABnoAiK5AN+8AlMoKyE8QSZgAyxkw7XkHA20AdhNyPbUYxjIAgQcGiLMAmi8Aywygt2KjsbW67mAApTsAhJEIVg8AegoL3u4A3p2gf5QxAL0AJ+cAbTSAaScAln8ANyMAhHSRhAAG3yiw71QwlJMHDQkJJCcJ1GUIEQgAaUYAuZYLzCwA2pwAtr5A3xEw/ygw6vMAWI0GdHiwiqsHXrEA6/kJhmSxAN4AN4YJQNUARycAhngANn4AYOsKyLBwzX8EKqQAghcA7EIAhX9wABQAJiEAPv6gi8YAy8EKDpmgnPAI9vSMTrEA/pAAxT0HQrIAZ/sHjIII70/zNPGIqFFfADePADFcAAHTAEXmBNV1AE7lsWmMsLdWw/KRAWjEAFHnCdRggEfbADcBltvyCAhLoIooAO8LAOwoAM70AO3ADIvzAFb8CwdbAIoEDGrpi3rxAJaFAQB1kEa9ABVZWoIgADNYAEERAvNsAHreDJqRDK28BjQpAB7Qq2hGAEiPDDxgA7JImVyBA/2bBncpgJ0BqraAAG2DvGnAAMcigKblQHWMgAEdACTuAAWgADDOBkFAADGhDGm5IECWMLr5AC6pAMgiAEHuDG3xwATzAJRuAIq4UM2YAO6SCAr1q100AIk/AMyekN5MAL4AkGhqxaxvAGVOkIk2A/dv+gwQ3QAVWgCAvgBTPAACTHABkVLya7CI4QyucgCFTwAh4wq9+8AsyIBqKwWgS8vT/IwhsbDo6gx+Tgiuag0kkwBWDwBogwC8YACJzADM9gC7r6BgOBABJw00xUAWugAgxwhomKAPGSBG+wKGJhBkSQApHwB+xa0ai8A4fGC8IwgeiwDtkAP39MD/GADLCzRuRoC2Lw1WCABn+AVsAgDD1sx5MgBgOxACoQASOwBoMwAnSAAw5QAwe5yTsLBuJBIUIgMMAADAxc0QGQ0Ttg1ojNCZkQDkLIvPFQ3O8wjrP7Ptxg2UbwBFggBnxw1sLAC1vnM4TASwogAY4kAp3Gukz/gAJIQI14vSkmYAIi9h0ZkJXZkA2O97XfjAWYsALcyQu28AeaKgy24A7yQMTFDQ/tEA7hkA7pgJiGitn+CQypUAeR8AuRkAlNJxAN8AE/IAEwQAZyoAOK8AVVcKU6CxQZcA4BcxtYWcuzew2t4N5GSAJsAAQIE66c0AeTsM6i4A7zMA/yELnyYJgWGQ7GIApisAOHhwVvMAnAYAssjQiEkAlyCQANsLo+4AAqsAVu0JeDcAhugAKT+hPBew5mgBMmkFYI/gyLYAzc8AtG0NR9AASBulro+gr1IwztIA82LuftIJ2cQObGwAliYANBDriIbQh1kAkL4y0NUANOgANc/zoCqPsDkiBZW4DQQBG8xtHlKcAL64gIduANyMCDyECy7QoEjmDYmaBC6YjSHl21NQ7ZYi6VeowMnDAFpOncYmCDnu0IyKCgxYkCZOBAk/wBNbAFTMCQkKDJQJECabxTiMijZN65rbV16UAOz0AIDgq2mBADfDDqQovSwBAOdRgP7RCS8hAOqYAGdSAKRT4JSRDrz50wZHznNoYFF7AGkuAHVdAACxABm6YFnyAJZICbNPECImEKSW1omECA3OBCttAIs0DG3CAMlFCERvilJJDkqSB8PruiCMyH61Cuz7DDrWwLDrwCh/cEaDAJOjMNr/ALuyoBW4AHinAGIudkGv+Aun6wBidMEz0gFkntNaAu6LXoDbhrCNNJwLYwCUgahd4CbIgmCpEQ1bBDrvBAP9NAtekgh6uImkmwAkZweGCwuLPAC7+goFiAAodAB3TgAxSghR+wAD9wBVvw5EDxApTuNQCQBFBb7hztnXVQB5QwC8+QCogwq7hl2JGw9Igwlaf4owCODs9gDkScDszAh31jBFof5IBACZkACgtjBxXgBWuwBl5AATqwBl8wAgyQci0A6TVh7CYjEDbwDI7wB7xoC9MgDITQBzOaCbhbBw+8A3WwA0+g4JywMH/A6u7Dg9nQ+OsgP0/c8Jyw4pXv3PtECRb6BoVeBT5QASIgBX7/IAl7oAMMgAIq8EjvmQTG8J39KQqSnQqO8AZT8Aev8PxZjwWhDgZ24Aic8J+L0Ae/BxCZroUD9uxXunfw3K0Ld40XpicAVgBJ8uQJmj+E7IjBIkHHkAsNfvhhVUtREQUjKiwA0NLlS5gxZc6kCQbYmydY6mQCxssWKTs23oByxCYJlkU2jtpBNGkSoUyE+vQR6O3VtWvw5MVzl84bMluOIk40kmQKFjYcO45owEABijWogtXyMwMBhQQ09e7l63LHs1RggEzpE2lWJFGc6qwQk6kRG7SYViQB8wYQpaec/tRB9CqbuYbX4s2T964duWmp2LhcUfbJ2SlJGrQYosVJ/wMpknLlkqSlwwEDfYUPf/lE2KQnOwg7SgVoEaEpAIw4h9zHRoyKYvo4RcwJUapp4UAzu/buXTZuzIThmhS9ZeuKFmXX0ELnkJwPcljl+uRGR4MDiBOwryccAgMA5f5whJTNwEgCwTcMYaOPHVqy4YnKIslkQ04i4eUab8xBh5x04FnHFmEieaUVQx50yYaypjDCARi22GOTTeiAgY5PUJGDCRTyGnDImcQIhxlEHjSCMMT4EOMJIAAgQTs2HFnhPSOwAAOQSSKxw5FMXhFmoHCmQccdc3hhhhdeODnwJfiemK0KOi5hBRU/ivhCji106IAlIgN9SYxrmJnFxSULm/+EIxteTKvClkgwAogn3kAEETDYQIQTW5C5ZhpevEknHayY+SWSiGCCMQIV6IQElVxigeSLH3xAwQFABRV0ildSocRF6cD4IxJHBFMViytb2sAI7MTgo46j+IgkFVtsyQSQV4whxxtbcBGlD2BfqqAGL+iAhJVYakHlkCtUkMCBAHUNFAwwUjFkCkhbogwQRwBJDqYYjIDpSiDQAqNZRDZ8hRNORPGGm2mEeaWRVGFyYIYzBrEz3Vg2ceOHDxhIIFx5h4MsiSRiSPalLAFpRAwAYohJZjgRfEIMZimbihBbfvHpGWZ6xQTnmCRAYg1FRkm3lo73kOKDBQzBpY+Sq37/iTI+MJUyppXhzCkG7MCoQww2UkklYTYjWYSPil2iwAk6JEGlllzUVYQOKSpgQAxRxiTZ6kCfmCVTQtrmS9IrSaAMDbI5yYSqXglhwz2XGpDAixtjqTsWSfw4YwgK3sBCjEVwQQYLwEvGohU00DBKwGQ3UI5sPhxB7JVeEXndJQdGqOLGkmIZ5ZA1fohggT/+wCIJNED5BZk3UydyCmQWRUtg4lYOmw9DDPljll+EQaYV1FtyoAMf6oNkE1Q+OeTzDhowhI8pIil/CkBAGVx6IrFQhQ0wTKFFgrqQGOogNlGk4hWqiER0FhABFPjgCmugAx7w4IUr4GAlT2ADKNCQ/4QnucQIW4II/wSUhFdMAgxGaN7fBLQDDInhD4vIhCgAgYUDLIACI9CBFLbwQyfYqgEsMcITpBadJ2DPJZQSgwtNKBMjgGIRYlCKIUDhxOHEAAhLogS12PCEBDSgAh9AAQ6GMAQfwKADuBIhFpijpCjFBAhzfKJeKlIULFxHDMjgRKN0tYMOvgIMWEDAAhxAAQ18YAQi+IAG3qUAmGSphC3JVx2HYwNMriBZT+iDMezQNSJN5DUJWEADIiABClAAlbiCJBSxkIo4AsCPlhQUFp7RCsMRyQAIIGUEfOkABixgAQhAAF+AAIqXzJKWREKDMSYBSgERoAAHQIACGuAAXP8N8wDK3AsQMLHMqtkSFNGLJgEMcAB08lIBxAQDGvoABmjSBAiGAGfJnmAMQFBOOATgpzQLYAADFAAABWNDI4DBDE5gUSZAWE09dZWEWVBROAMYQD8LQAA5GpASoniFIWgmnII59KGiUGLV9mWH5QkICJUU6YCAQCHAJYEQuCMKN43ZUkHtAGaAAwIlCsKLnRInljgd0IUAtwMs8KERuCBFLvliU6IKx6hWMwIhQGG2Rih0JlCN6lNLqqsnLIIXqmBOHT7a1TpydUA7MIIhePGMayDjFU5Fq/TUShwb8AETqeBFmDp617oGtiVGeIMjXvGLV/xhCl8UbGNnAkhV+CxRFY14ww5Y6ljM7oAPpBBFJPqQRMyG9iUMdQQlEGGEy4rWsUb4AyZQq1rYSod0Wo0tWo8y1NqGNgmpzW1jjRDP3goWsMHt6nCJS1TjHle5jQ0IADs="

def click_input_files_dialog():
    progress.set(40)
    file_type = [("", "*")]
    input_images_path = filedialog.askopenfilename(filetype=file_type, multiple=True)
    files_entry.set(file_separate_sign.join(input_images_path))

def click_output_folder_dialog():
    progress.set(10)
    init_dir = os.path.abspath(os.path.dirname(__file__))
    output_folder_path = filedialog.askdirectory(initialdir = init_dir)
    folder_entry.set(output_folder_path)

def round_image_target(input_images_path_list, output_folder_path):
    progressbar.pack(fill="x", side="left")
    progress.set(0)
    for i, input_image_path in enumerate(input_images_path_list):
        round_image(input_image_path, output_folder_path)
        next_progress = ((i + 1) / len(input_images_path_list)) * max_progress
        progress.set(int(next_progress))
    messagebox.showinfo("完了", "ヒャッハーーっ❕❕\n俺様がズタズタに切り裂いてやったぞ❕❕\n次の獲物は貴様かもな❕❕震えて眠るんだな❕❕ヒャッハーーっ❕❕")
    progressbar.pack_forget()

def exe_round_image():
    input_images_path_list = files_entry.get().split(file_separate_sign)
    output_folder_path = folder_entry.get()
    if not input_images_path_list or len(input_images_path_list) > 0 and not input_images_path_list[0]:
        messagebox.showerror("エラー", "ヒャッハーーっ❕❕\n入力画像が選択されてないぜ❕❕\nさすがの俺様も無いもんは斬れねえぜ❕❔")
        return
    if not output_folder_path:
        messagebox.showerror("エラー", "ヒャッハーーっ❕❕\n出力フォルダが選択されてないぜ❕❕\n斬った獲物達をこの俺様が持って帰って喰っちまうぜ❕❔")
        return

    t = threading.Thread(target=round_image_target, args=(input_images_path_list, output_folder_path))
    t.start()


if __name__ == "__main__":

    # root
    root = Tk()
    root.tk.call("wm", "iconphoto", root._w, PhotoImage(data=icon_data))
    root.title("画像丸々カットくん")

    # Frame2
    frame1 = ttk.Frame(root, padding=10)
    frame1.grid(row=0, column=1, sticky=E)

    IFileLabel = ttk.Label(frame1, text="入力画像 (複数可)", padding=(5, 2))
    IFileLabel.pack(side=LEFT)

    files_entry = StringVar()
    IFileEntry = ttk.Entry(frame1, textvariable=files_entry, width=30)
    IFileEntry.pack(side=LEFT)

    IFileButton = ttk.Button(frame1, text="参照", command=click_input_files_dialog)
    IFileButton.pack(side=LEFT)

    # Frame1
    frame2 = ttk.Frame(root, padding=10)
    frame2.grid(row=2, column=1, sticky=E)

    IDirLabel = ttk.Label(frame2, text="出力フォルダ", padding=(5, 2))
    IDirLabel.pack(side=LEFT)

    folder_entry = StringVar()
    IDirEntry = ttk.Entry(frame2, textvariable=folder_entry, width=30)
    IDirEntry.pack(side=LEFT)

    IDirButton = ttk.Button(frame2, text="参照", command=click_output_folder_dialog)
    IDirButton.pack(side=LEFT)

    # Frame3
    frame3 = ttk.Frame(root, padding=10)
    frame3.grid(row=5,column=1,sticky=W)

    button1 = ttk.Button(frame3, text="実行", command=exe_round_image)
    button1.pack(fill= "x", padx=150, side="left")

    # Frame 4
    frame4 = ttk.Frame(root, padding=10)
    frame4.grid(row=6, column=1, sticky="w")
    progress = IntVar(value=0)
    progressbar = ttk.Progressbar(
        frame4,
        length=380,
        maximum=max_progress,
        mode="determinate",
        variable=progress,
    )

    root.mainloop()
# pyinstaller ImageRounderApp.py --onefile --noconsole --icon=icon.ico --name 画像丸々カットくん